package org.codecop;

import static org.junit.Assert.*;

import org.junit.Test;

// use Eclipse Wizard to generate the stub

/**
 * Session 2: GreeterTest - First Test method against Greeter.
 */
public class Session1_GreeterTest {

    // first run - fails, then delete (generated by Eclipse when using the Wizard)

    //    @Test
    //    public void testGreet() {
    //        fail("Not yet implemented");
    //    }

    // change to reasonable name and really test the greet method

    @Test
    public void shouldReturnHelloName() {
        assertEquals("Hello Peter", new Greeter().greet("Peter"));
    }

    // add another test method, what about null?

    @Test
    public void shouldReturnHelloForNull() {
        assertEquals("Hello", new Greeter().greet(null));
    }

    // add another test method, what about blanks?

    @Test
    public void shouldIgnoreWhitespace() {
        assertEquals("Hello Peter", new Greeter().greet(" Peter "));
    }

}
