name: Test Python 2 + UnitTest

on:
  push:
    paths:
      - 'python-unittest/**'
      - '.github/workflows/python-unittest**'
    branches:
      - with_assertions
  pull_request:
    paths:
      - 'python-unittest/**'
      - '.github/workflows/python-unittest**'
    branches:
      - with_assertions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'

    - name: Test
      working-directory: python-unittest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ./run_first_session.sh
        ./run_tests.sh
